version: "2"
services:
  testDb:
    container_name: testDb
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres-volumes:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: philipt
      POSTGRES_USER: philipt
      POSTGRES_DB: postgres
    networks:
      - myNetwork
networks:
  myNetwork:
volumes:
  postgres-volumes:
